# Generated by Django 5.2 on 2025-06-11 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_aluno_ativo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aluno',
            new_name='Funcionario',
        ),
    ]
