# Generated by Django 5.2 on 2025-06-12 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_rename_aluno_funcionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=150)),
                ('editora', models.CharField(max_length=100)),
                ('ano_publicacao', models.PositiveIntegerField()),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('genero', models.CharField(choices=[('romance', 'Romance'), ('ficcao', 'Ficção'), ('nao_ficcao', 'Não Ficção'), ('biografia', 'Biografia'), ('poesia', 'Poesia'), ('aventura', 'Aventura'), ('drama', 'Drama'), ('outro', 'Outro')], max_length=20)),
                ('quantidade_disponivel', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='curso',
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='genero',
            field=models.CharField(choices=[('romance', 'Romance'), ('ficcao', 'Ficção'), ('nao_ficcao', 'Não Ficção'), ('biografia', 'Biografia'), ('poesia', 'Poesia'), ('aventura', 'Aventura'), ('drama', 'Drama'), ('outro', 'Outro')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
