# Generated by Django 5.2 on 2025-06-27 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0008_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='status_ocorrencia',
            field=models.CharField(choices=[('normal', 'Normal'), ('perdido', 'Perdido'), ('danificado', 'Danificado')], default='normal', max_length=20),
        ),
    ]
