# Generated by Django 5.2 on 2025-06-27 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0009_emprestimo_status_ocorrencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='bloqueado',
            field=models.BooleanField(default=False),
        ),
    ]
