# Generated by Django 5.1.7 on 2025-07-03 00:23

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0010_cliente_bloqueado'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='foto',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='fotos/alunos', variations={'medium': (300, 300), 'thumb': (150, 150)}),
        ),
    ]
